# Generated by Django 5.0.7 on 2024-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_member_status', models.CharField(choices=[('member', 'Бот активен в личном чате с пользователем'), ('kicked', 'Бот был заблокирован пользователем в личном чате')], default='member', max_length=50)),
                ('username', models.CharField(max_length=255, verbose_name='пользователь')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия')),
                ('language_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='язык')),
                ('is_premium', models.BooleanField(default=False, verbose_name='премиум')),
                ('added_to_attachment_menu', models.BooleanField(default=False, verbose_name='добавил бота в attachment menu')),
            ],
            options={
                'verbose_name': 'Пользователь ',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
